## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [1]:
import numpy as np

In [6]:
n_array = np.arange(12,38)
print(n_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
n_array2 = np.array([[1., 1., 1.],[1., 1., 1.],[1., 1., 1.]])
n_array2_padded = np.pad(n_array2,pad_width=1,mode='constant')
print('Original array:\n',n_array2)
print('Padded array:\n',n_array2_padded)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Padded array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [31]:
list = [1,2,3,4,5,6,7,8]
list2array = np.array(list)
print('List to array :\n',list2array)
tuple = ([8,4,6],[1,2,3])
print('Tuple to arrray :\n',np.asarray(tuple))

List :  [1, 2, 3, 4, 5, 6, 7, 8]
List to array :
 [1 2 3 4 5 6 7 8]
Tuple to arrray :
 [[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
 [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [41]:
#C = (°F - 32) x 5/9 
F = np.array([ 0,   12,   45.21, 34,   99.91])
print('Values in Fahrenheit degrees:\n',F)
print('Values in  Centigrade degrees:\n',(F-32)*5/9)

Values in Fahrenheit degrees:
 [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [155]:
#program to find the number of elements of an array, length of one array element in bytes 
#and total bytes consumed by the elements.
def exercise5(nr17):
    print('Size of the array: ',nr17.shape[0])
    print('Length of one array element in bytes:',nr17.itemsize)
    print('Total bytes consumed by the elements of the array: ',nr17.nbytes)

nr17 = np.array([1.,2.,3.])
exercise5(nr17)

Size of the array:  3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array:  24


## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]



In [69]:
nr6 = np.array([10,10,20,20,30,30])
print('Original array:\n',nr6)
nr6_unique = np.unique(nr6)
print('Unique elements of the above array:\n',nr6_unique)

nr6_1 = np.array([[1,1],[2,3]])
print('Original array:\n',nr6_1)
nr6_1_unique = np.unique(nr6_1)
print('Unique elements of the above array:\n',nr6_1_unique)

Original array:
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


## Exercise 7: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
nr7 = np.array(range(1,10))
print('Original array:\n',nr7)

print('Reshape array to 3by3:\n',nr7.reshape(3,3))

Original array:
 [1 2 3 4 5 6 7 8 9]
Reshape array to 3by3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [70]:
print(np.linspace(2.5,6.5,30))

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [81]:
arr9_1 = np.array([10,20,30])
arr9_2 = np.array([40,50,60])
arr9 = np.stack((arr9_1,arr9_2),axis=1)
print('Converted array\n',arr9)

Converted array
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [98]:
narr10 = np.zeros((5,5))
print('Original array:\n',narr10)
arr10 = np.arange(0,5)
# method 1
print('Row values ranging from 0 to 4.\n',narr10+arr10)
#method 2
print('Row values ranging from 0 to 4.\n',np.add(narr10,arr10))

Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
Row values ranging from 0 to 4.
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [147]:
narr11 = np.arange(0,100)
# method 1
narr11_1 = narr11[(narr11%3==0) | (narr11%5==0)]

#method 2
narr11_2 = narr11[np.where((narr11%3==0) | (narr11%5==0))]
print('method 1\n',narr11_1)
print(narr11_1.sum())
print('mehtod 2\n',narr11_2)

print(narr11_2.sum())

method 1
 [ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318
mehtod 2
 [ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [153]:
n1 = np.array(range(0,4))
n2 = np.array(range(0,8)).reshape(2,4)

print('One dimensional array:\n',n1)
print('Two dimensional array:\n',n2)
for n in n2:
    for x,y in np.nditer([n1,n]):
        print('{0}:{1}'.format(x,y))

One dimensional array:
 [0 1 2 3]
Two dimensional array:
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [165]:
#NumPy program to replace all elements of NumPy array that are greater than specified array.
def replace_gt_n(narr13,n):
    narr13_1 = np.where(narr13>0.5,0.5,narr13)
    print('Original array:\n',narr13)
    print('Replace all elements of the said array with .5 which are greater than .5\n',narr13_1)

narr13 = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])
    
replace_gt_n(narr13,0.5)

Original array:
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [242]:
narr14 = np.array([[]])
narr14_1 = np.array([np.append(narr14,np.array([10,20,30]))])
print(np.array([[10,20,30]]))
print(narr14_1)
narr14_1 = np.append(narr14_1,np.array([[40,50,60]]),axis=0)   # axis=1 appends the new array in the row

narr14_2 = np.array([np.append(narr14,[10,20,30])])
print(narr14_2)
narr14_2 = np.append(narr14_2,[[40,50,60]],axis=0)
print('Empty array:\n',narr14)
print('After adding two new arrays:')
print('Method 1:\n',narr14_1)
print('Method 2:\n',narr14_2)

[[10 20 30]]
[[10. 20. 30.]]
[[10. 20. 30.]]
Empty array:
 []
After adding two new arrays:
Method 1:
 [[10. 20. 30.]
 [40. 50. 60.]]
Method 2:
 [[10. 20. 30.]
 [40. 50. 60.]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [268]:
#NumPy program to join a sequence of arrays along a new axis.
def join_seq_array(arr1,arr2):
    print('Original arrays:')
    print(arr1)
    print(arr2)
    print('Sequence of arrays along a new axis:')
    print(np.vstack((arr1,arr2)))

arr15_1 = np.array([1,2,3])
arr15_2 = np.array([2,3,4])
arr15_3 = np.vstack(arr15_1)
arr15_4 = np.vstack(arr15_2)
join_seq_array(arr15_1,arr15_2)
join_seq_array(arr15_3,arr15_4)

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
Original arrays:
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
